name: Ejecutar script de Python

on:
  schedule:
    - cron: '5 3 * * *' # Ejecutar todos los días a las 00:00 UTC

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Versión de Python que quieres usar
      - name: Ejecutar script de Python
        run: python agregarTabla.py # Nombre del archivo Python que quieres ejecutar
